#ifndef BIREME_GAZELL_CONFIG_H
#define BIREME_GAZELL_CONFIG_H

#define BIREME_NUM_KEYS 34

#define BIREME_GZLL_PIPE_0_ADDR 0x01020304
#define BIREME_GZLL_PIPE_1_ADDR 0x05060708

#define BIREME_LEFT_HAND_PIPE 0
#define BIREME_RIGHT_HAND_PIPE 1

#define BIREME_KEEP_ALIVE_TIMEOUT 125 /* ms */

#define BIREME_GZLL_ACK_PAYLOAD_LEN 1
#define BIREME_GZLL_KEY_PAYLOAD_LEN ((BIREME_NUM_KEYS-1)/8 + 1)
#define BIREME_GZLL_BAT_PAYLOAD_LEN 1
#define BIREME_GZLL_DATA_PAYLOAD_LEN (BIREME_GZLL_KEY_PAYLOAD_LEN + BIREME_GZLL_BAT_PAYLOAD_LEN)

#endif 